version: '3.9'

services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    env_file:
      - nginx.env
    volumes:
      - ANY:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    restart: always

  web:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - web.env
    expose:
      - 8000
    restart: always

volumes:
  ANY: